version: '2'
services:
  bmscrsii-app:
    image: bmscrsii
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://bmscrsii-mysql:3306/bmscrsii?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://bmscrsii-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://bmscrsii-elasticsearch:9200
    ports:
      - 8080:8080
  bmscrsii-mysql:
    extends:
      file: mysql.yml
      service: bmscrsii-mysql
  bmscrsii-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: bmscrsii-elasticsearch
